// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMXeWsRioZCqhfP4FoKt6W4RxpXU0zGf0',
    appId: '1:722794013211:web:bd123a33c63203a89c4ebe',
    messagingSenderId: '722794013211',
    projectId: 'planner-app-140d2',
    authDomain: 'planner-app-140d2.firebaseapp.com',
    storageBucket: 'planner-app-140d2.firebasestorage.app',
    measurementId: 'G-52LPRFVVZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA19kGwvUraLZauNEv8OhGRAjHdWxw3vq4',
    appId: '1:722794013211:android:0ccbfa0121907e0d9c4ebe',
    messagingSenderId: '722794013211',
    projectId: 'planner-app-140d2',
    storageBucket: 'planner-app-140d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg4qG7pShboH270lggGs5BcM8sP2EhV_E',
    appId: '1:722794013211:ios:28d58248908798699c4ebe',
    messagingSenderId: '722794013211',
    projectId: 'planner-app-140d2',
    storageBucket: 'planner-app-140d2.firebasestorage.app',
    iosBundleId: 'com.example.survey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg4qG7pShboH270lggGs5BcM8sP2EhV_E',
    appId: '1:722794013211:ios:28d58248908798699c4ebe',
    messagingSenderId: '722794013211',
    projectId: 'planner-app-140d2',
    storageBucket: 'planner-app-140d2.firebasestorage.app',
    iosBundleId: 'com.example.survey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMXeWsRioZCqhfP4FoKt6W4RxpXU0zGf0',
    appId: '1:722794013211:web:1cf82d04c944a1be9c4ebe',
    messagingSenderId: '722794013211',
    projectId: 'planner-app-140d2',
    authDomain: 'planner-app-140d2.firebaseapp.com',
    storageBucket: 'planner-app-140d2.firebasestorage.app',
    measurementId: 'G-9CT7JNB395',
  );
}
